name: Control Table Data Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  control-table-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Pull down this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.108
          npm install --only=dev
      - name: Ingest data
        run: node ./control_table_data_ingest/ingest.js
      - name: Commit processed data
        run: |
          git config --global user.name 'MITRE SAF'
          git config --global user.email 'saf@groups.mitre.org'
          git add ./src/assets/data/mitre-saf-control-mapping.json
          git commit -m 'Automated ingestion of profiles'
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
