name: Control Table Data Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  control-table-ingest:
    runs-on: ubuntu-latest
    name: Control table ingest
    steps:
      - name: Pull down this repo
        uses: actions/checkout@v2
      - name: Ingest and process data
        uses: docker://mitre/saf-baseline-ingestion
      - name: Commit processed data
        run: |
          git config --global user.name 'MITRE SAF'
          git config --global user.email 'saf@groups.mitre.org'
          git add ./src/assets/data/baselineProfiles/
          git add ./src/assets/data/baselines.json
          git add ./src/assets/data/mitre-saf-control-mapping.json
          git commit -s -m 'Automated ingestion of profiles' || true
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
